title: Pytorch LM-LSTM-CRF Ner config for Acharya
Owner: Liyuan Lucas Liu
author: Vimal Menon
cmd:
        train: train_ner.sh
        eval: eval_ner.sh
        type: pipe
        in: file
        out: stdout
